Semantic-Org/Semantic-UI-Ember

addon/components/ui-dropdown-item.js, addon/components/ui-dropdown.js, addon/components/ui-popup.js, addon/views/ui-modal.js
This is if fix for issue #8.
It takes advantage of the Ember Run Loop to wait until after the new dropdown items render before re-initializing the Semantic component. After this re-initialization, the items are now selectable and everything works as expected.
=> Re-Initialize ui-dropdown after content changes and the items re-render.

addon/components/ui-dropdown-item.js, addon/components/ui-dropdown.js, addon/components/ui-popup.js, addon/views/ui-modal.js, package.json
This is a fix for issue #13.
For some reason, using Semantic's `set selected` command wasn't properly updating the dropdown when the `value` changed. Switching to `set value` corrects the issue.
=> Use `set value` rather than `set selected`

addon/components/ui-dropdown.js
Upon further testing, `set value` wasn't behaving reliably either. This method is the only one that seems to perform reliably in all situations (even though it's running more code).
=> Use `set selected` again but call `set_value` after re-render

addon/mixins/modal.js, package.json
This should fix the transition error message. Also now if the controller has an action for approve or cancel, that controller is now responsible for closing the modal.
Also, we are now passing in the view, the proper way to close the modal is to call back to the view with 
```
view.execute('hide')
```
Then the events happen in the right order for semantic
=> Fixing on hide error

README.md
Javascript should be obvious.
Enclosing `div.ui.modal` in template example is unnecessary and breakes the example.
=> Fixes example issues for modal in README

addon/components/ui-dropdown.js
Added code to the `afterRender` handler to simply return if the view `isDestroyed` or `isDestroying` to prevent console errors.
The code needs to be in the `afterRender` handler rather than before registering as the view may not be in the process of being destroyed until we get to the handler function.
=> Fix onContentChange handler when destroyed or destroying

addon/mixins/application-route.js
Occasionally, this.controllerFor(name) returns 'undefined' which will then throw an error when attempting to set the model.
This is a fallback that will throw an error anytime the controller is 'undefined' or otherwise blank
=> Fallback for Controller = 'undefined'

README.md
Added in a missing equal sign for ui-dropdown usage docs.
=> Small fix to onChange action syntax for ui-dropdown

addon/components/ui-dropdown.js, tests/integration/components/ui-dropdown-test.js
This is a minor logic change for dropdown. If you bind to value it will call `set value` on initialize and if you bind to selected it will call `set selected` on initialize. The logic within *Semantic-UI* indicates that setting a value updates the value but doesn't refresh the UI and setting selected updates both.
- Updated dropdown so it sets both "selected" and "value" depending on what was passed into the component
- Removed the initial element set, not sure if this is needed anymore it was a pretty old and we don't have a test that indicates an issue
=> Binding a dropdown to selected instead of value

addon/mixins/base.js
When trying to use `error` property in some modules like the `ui-search` it gets ignored
Since this prop is ignored we can't override these configs, like error messages
```
// component.js
error: {
noResults: 'foo bar'
}
// template.hbs
{{ ui-search error=error }}
```
=> removing error from ignored properties to use in the setting of the modules

README.md
Hi. I've used this semantic-ui binding and found that README.md isn't up to date. Binding to ui-dropdown `value` property produces runtime deprecation warning that suggests to bind `selected` property instead, so I updated README.md according to this warning.
=> Deprecation warning for ui-dropdown

addon/mixins/base.js, package.json
As of ember 2.8.0-beta.1, `Enumerable.contains()` has been depreciated
in favor of `Enumerable.includes()`. Semantic-UI-Ember uses the
depreciated function in several places, this simply replaces those
usages. http://emberjs.com/deprecations/v2.x/#toc_enumerable-contains
Thanks #Panman8201 for the initial pull request #121
=> Fix Enumerable#contains deprecation warnings

ember-cli-build.js, index.js, package.json, utils/build-tests.js, utils/generation.js
Adds two configuration options. One for the path to the `dist` folder of
Semantic. The other option to specify the theme used for images and
fonts.
Note that this does not add support for importing files outside of the
build tree (e.g. `bower_components`). One can use `bower link` for local
projects.
=> Allow custom semantic-ui builds

package.json
Containing apps break when polyfill is not installed.
When installing, the polyfill is not installed, while the other polyfills are.
=> Move ember-string-ishtmlsafe-polyfill to dependencies

addon/mixins/base.js, package.json
Latest release places the polyfill in the “native” location, instead of needing to import the function.
Note: This is part of an effort to get all users of the polyfill updated.. https://github.com/workmanw/ember-string-ishtmlsafe-polyfill/issues/5
=> Update isHTMLSafe polyfill dep

addon/mixins/base.js, addon/mixins/checkbox.js, ember-cli-build.js, index.js, package.json, tests/dummy/config/environment.js
Upgraded based on guides defined here: 
- https://gist.github.com/kratiahuja/d22de0fb1660cf0ef58f07a6bcbf1a1c
- https://github.com/ember-fastboot/ember-cli-fastboot/issues/387
Also reused work from this PR https://github.com/Semantic-Org/Semantic-UI-Ember/pull/184
=> v1 fastboot upgrade

addon/mixins/base.js
In fastboot mode, `Accessing `this.element` is not allowed in non-interactive environments (such as FastBoot).` error is thrown due to the calling of `getSemanticScope` (since it tries to access the jQuery element) via the `getSemanticModule` call present in the `execute` method.
Follow up to #204
Resolves #100
=> Skip `getSemanticModule` in fastboot mode

tests/dummy/app/templates/modules/sidebar.hbs
- Action in sidebar example is passed correctly as an action and not as a string.
=> Sidebar example typo

index.js, package.json
Currently only `icons.*` font files are imported, whereas semantic-ui now also ships with `outline-icons.*` and `brand-icons.*`. This PR uses `walk-sync` to find all font files in the specified directory and copies them over.
=> Copy all icon fonts assets

index.js
See #231 for additional information. Beware that I've removed the following config resolvers:
```
(app && app.project.config(app.env)['SemanticUI'])
|| (app && app.project.config(app.env)['semantic-ui-ember'])
```
I don't know what these do and where they get their config from. The change proposed in this PR reflects the actual documentation and has been tested on ember-cli 3.0.
=> Resolve issue with resolving configuration

addon/components/ui-search.js
I did not like the solution. I'm accepting suggestions.
API `object.search('set source', []);` don't working :confused: 
Fix: https://github.com/Semantic-Org/Semantic-UI-Ember/issues/181
Simulation: https://ember-twiddle.com/56f28ca7aecd9e6fc17b824a900596e3
=> Solve bug ui-source (#181)

index.js, tape-tests/utils/get-default-test.js
It fixes a bug where the consuming app's options set in `ember-cli-build` were not being read by this addon.
The ember-cli-build.js [configuration options](http://semantic-org.github.io/Semantic-UI-Ember/#/modules/usage) were not being used at all by the addon due to a logic mistake in the JavaScript. For example, the `css` boolean below made no difference, and the addon kept using the default styles. Likewise, naming specific `source` paths had no effect.
```javascript
// this didn't work
var app = new EmberApp(defaults, {
// Add options here
SemanticUI: {
import: {
css: false,
}
}
});
```
Here's the problem in `index.js`. `options` evaluates to `true` or `{}`, when it should evaluate to to an object of the options, like `{import: { css: false } }`. `getDefault` is a function that tries …
=> Bugfix: use addon config options #238

addon/mixins/base.js, config/optional-features.json, package-lock.json, package.json
Upgrading Ember to 3.9.0 version, tons of deprecation these warnings started to appear: 
```
14:21:38.000 DEPRECATION: Using this.$() in a component has been deprecated, consider using this.element [deprecation id: ember-views.curly-components.jquery-element] See https://emberjs.com/deprecations/v3.x#toc_jquery-apis for more details.
```
Following the [suggested solution](https://emberjs.com/deprecations/v3.x#toc_jquery-apis
) on the ember guide, i've explicited the version of `@ember/jquery` and `@ember/optional-features` in the dependecies of the project. Although Semantic-UI-Ember is not a wrapper of a Jquery Plugin, it strictly depends on jquery.
=> JQuery Version explicit for suppress deprecation warnings
